### PR TITLE
Update config.inc.php

### LINKED ISSUE #94: 404 on bootstrap-datepicker.en.min.js
Installing WP on a fresh centos8, this resource get a 404 when loaded, it's because it's actually named bootstrap-datepicker.en-GB.min.js.

Will try to provide a PR.

### PR DESCRIPTION
**Pull request by sophieqc**
use en-GB instead of just en should fix #94

### CODE REVIEW

**Comment by coudot** [comment]
I think there should be a better way to fix this. as the configured lang is also used to load main translation file, which is `lang/en.inc.php`

So we should maybe add a second option for datepicker lang, which would be the main lang if not defined.

**Comment by sophieqc** [comment]
Maybe a simple symbolic link to en-GB to en would be enough.

**Comment by coudot** [comment]
Here is my proposal:
```
diff --git a/htdocs/index.php b/htdocs/index.php
index c67167e..b92a637 100644
--- a/htdocs/index.php
+++ b/htdocs/index.php
@@ -84,6 +84,11 @@ foreach ($messages as $key => $message) {
     $smarty->assign('msg_'.$key,$message);
 }
 
+# Adapt lang for datepicker
+$lang_datepicker = $lang;
+if ( $lang === "en" ) { $lang_datepicker = "en-GB"; }
+$smarty->assign('lang_datepicker',$lang_datepicker);
+
 # Other assignations
 $search = "";
 if (isset($_REQUEST["search"]) and $_REQUEST["search"]) { $search = htmlentities($_REQUEST["search"]); }
diff --git a/templates/footer.tpl b/templates/footer.tpl
index 433465f..2a421b9 100644
--- a/templates/footer.tpl
+++ b/templates/footer.tpl
@@ -7,7 +7,7 @@
 <script src="vendor/jquery/js/jquery-1.10.2.min.js"></script>
 <script src="vendor/bootstrap/js/bootstrap.min.js"></script>
 <script src="vendor/bootstrap-datepicker/js/bootstrap-datepicker.min.js"></script>
-<script src="vendor/bootstrap-datepicker/locales/bootstrap-datepicker.{$lang}.min.js"></script>
+<script src="vendor/bootstrap-datepicker/locales/bootstrap-datepicker.{$lang_datepicker}.min.js"></script>
 {if $use_datatables}
 <script src="vendor/datatables/datatables.min.js"></script>
 {/if}

**Comment by faust64** [comment]
Done. Would set `en-GB` whenever that javascript is not found.
(Shouldn't we PR on ltb-project, rather than here?)

**Comment by coudot** [comment]
Hello @faust64 

thanks for the update, you can indeed create a specific branch here to merge this PR, then open a PR on ltb-project.

**Comment by coudot** [comment]
PR done in https://github.com/ltb-project/white-pages/pull/98

**Pull request closed without merging**
